### ISSUE TITLE
Error in np.random.choice() when sampling categorical variable consisting of size-one np.arrays()

### ISSUE THREAD

**Issue by twallema** [vthorey/benderopt#7]
Problem: Attempting to sample from a categorial variable, defined as a list containing np.arrays (see example below), generates an error in the `np.random.choice()` function used to draw a sample in function `generate_samples_categorical()` in `~/stats/categorical.py`. The error message of the `np.random.choice()` function states that "a is not a 1-D variable". 

```python

control_handles_dict['Nc']['bounds_values'] = [ np.array([1.5]), np.array([2.0]), np.array([2.5]) ]

optimization_problem_parameters = [
    {
        "name": "x1",
        "category" : "categorical",
        "search_space" : {
            "values" : control_handles_dict['Nc']['bounds_values']
        }
    },
    {
        "name": "x2",
        "category" : "categorical",
        "search_space" : {
            "values" : control_handles_dict['Nc']['bounds_values']
        }
    },
]

some_obj_fun(**x):
    return x['x1'] + x['x2']

minimize(obj_fun, optimization_problem_parameters)
```

If one of the `np.arrays()` in `control_handles_dict['Nc']['bounds_values']` is swapped for another data type, f.i.,
```python
control_handles_dict['Nc']['bounds_values'] = [ 'a', np.array([2.0]), np.array([2.5]) ]
```
the error does not occur and `np.random.choice()` draws a sample from the above list.

Swapping `numpy.random.choice()` out for `random.choices()` in function `generate_samples_categorical()` in `~/stats/categorical.py` resolves the issue.

```python
import random

def generate_samples_categorical(values, probabilities, size=1):
    """Generate sample for categorical data with probability probabilities."""
    return random.choices(values, weights=probabilities, k=size)
```
Let me know if the above explanation is clear and thanks in advance.

**Comment by vthorey** [comment]
Thank you for your comment, I will take a look soon.

If you believe you fixed something feel free to open a Pull Request

**Comment by vthorey** [comment]
As it is a very specific issue I will not take action on this. An easy workaround would be avoiding this kind of mixed data types/
