### ISSUE TITLE
Specifying a variable is larger than another. 

### ISSUE THREAD

**Issue by ItayVortex** [vthorey/benderopt#8]
I'm using `minimize` and I have variables named `x` and `y`. Both in the closed range `[0, 10]`. Is it possible to give a constraint in which `y` is larger than `x`?
I can implement it on my own by returning a large value in my function but is there a more correct way to do that?

**Comment by vthorey** [comment]
The package does not support conditional constraints, so there is no way of doing this out of the box.

**Comment by Rizhiy** [comment]
@ItayVortex One work around is to add validation of variables at the start of your function and return `np.inf` if conditions are not met.

Not very efficient, but that should work.
